name: ShowItem
main: com.xiangouo.mc.showitem.ShowItem
version: 1.2
api-version: 1.15
author: XiangOuO_

commands:
  showitem:
    aliases:
      - si
    description: show item command.
permissions:
  showitem.use:
    description: show item permission.